name: CI output design

# ToDos:
# - artifact upload ERC/DRC

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # branches: [ main ]
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kiplot.yaml'
      - '.github/workflows/generate_output.yml'
  pull_request:
    # branches: [ main ]
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kiplot.yaml'
      - '.github/workflows/generate_output.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6

    steps:
    - uses: actions/checkout@v2

    - name: Run ERC
      run: |
        [ -f *.kicad_sch ] && kiplot  -d Fabrication_temp -s update_xml,run_drc -i
    #- name: Retrieve results
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: ERC-DRC_Output
    #    path: 'Fabrication_temp'

  DRC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6
    needs: ERC

    steps:
    - uses: actions/checkout@v2

    - name: Run DRC
      run: |
        [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp -s update_xml,run_erc -i
    #- name: Retrieve results
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: ERC-DRC_Output
    #    path: 'Fabrication_temp'

  Fabrication:
    name: Fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6
    # needs: ERC

    steps:
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Assign variables from project.properties to Env variable
      run: |
        cat project.properties >> $GITHUB_ENV  
    
    - name: Update the Schematic with the git hash
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!Git-${COMMIT}!" *.kicad_sch
        sed -i "s!<<project_name>>!${{ env.project_name }}!" *.kicad_sch
        sed -i "s!<<date>>!$(date +'%Y-%m-%d')!" *.kicad_sch 
        sed -i "s!<<ID>>!${{ env.ID_prefix }}${{ env.ID }}!" *.kicad_sch
        cp *.kicad_sch ${{ env.project_name }}.kicad_sch
    - name: Retrieve results from git hash update
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.project_name }}_Kicad_raw
        path: '${{ env.project_name }}.kicad_sch'

    - name: Run Schematic and BOM 
      run: |
        [ -f *.kicad_sch ] && kiplot  -d Fabrication_temp -s all  print_sch interactive_bom

    - name: Assign variables from project.properties to Env variable
      run: |
        cat project.properties >> $GITHUB_ENV 
    
    - name: Update the PCBs with the git hash
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!Git-${COMMIT}!" *.kicad_pcb
        sed -i "s!<<project_name>>!${{ env.project_name }}!" *.kicad_pcb
        sed -i "s!<<date>>!$(date +'%Y-%m-%d')!" *.kicad_pcb 
        sed -i "s!<<ID>>!ID: ${{ env.ID_prefix }}${{ env.ID }}!" *.kicad_pcb 
        cp *.kicad_pcb ${{ env.project_name }}.kicad_pcb
    - name: Retrieve results kicad_pcb with the git hash
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.project_name }}_Kicad_raw
        path: '${{ env.project_name }}.kicad_pcb'
    - name: Run PCB stuff
      run: |
        [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp -s all print_front print_back pcb_top_b pcb_bottom_b
        cd Fabrication_temp
        mv Schematic.pdf ${{ env.project_name }}_Schematic.pdf
        mv PCB_Bottom.png ${{ env.project_name }}_PCB_Bottom.png
        mv PCB_Top.png ${{ env.project_name }}_PCB_Top.png
        mv BoM/iBoM.html BoM/${{ env.project_name }}_iBoM.html
        mv PCB_Sheet/PCB_Back_Sheet.pdf PCB_Sheet/${{ env.project_name }}_PCB_Back_Sheet.pdf
        mv PCB_Sheet/PCB_Top_Sheet.pdf PCB_Sheet/${{ env.project_name }}_PCB_Top_Sheet.pdf
    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.project_name }}_Output
        path: 'Fabrication_temp'

    - name: Run STEP
      run: |
        [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp_step -s all step
    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.project_name }}_Output_STEP
        path: 'Fabrication_temp_step'