name: CI output design

# ToDos:
# - artifact upload ERC/DRC

# Controls when the action will run. Triggers the workflow on push or pull request
# events that happen on all branches
on:
  push:
    # branches: [ main ]
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kiplot.yaml'
      - '.github/workflows/generate_output.yml'
    tags-ignore:
      - '**'
  pull_request:
    # branches: [ main ]
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kiplot.yaml'
      - '.github/workflows/generate_output.yml'
    tags-ignore:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC-DRC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6

    steps:
    - uses: actions/checkout@v2

    - name: Run ERC & DRC
      run: |
        [ -f *.kicad_sch ] && kiplot  -d Fabrication_temp -s update_xml,run_drc -i
        [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp -s update_xml,run_erc -i
    #- name: Retrieve results
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: ERC-DRC_Output
    #    path: 'Fabrication_temp'

  # DRC:
  #   runs-on: ubuntu-latest
  #   container: setsoft/kicad_auto:dev_k6
  #   needs: ERC

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Run DRC
  #     run: |
  #       [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp -s update_xml,run_erc -i
    #- name: Retrieve results
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: ERC-DRC_Output
    #    path: 'Fabrication_temp'

  Fabrication:
    name: Fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6
    # needs: ERC

    steps:
    - name: Update system repositories, Install Required Libraries
      run: |
        apt update
        apt -y install git
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Assign variables from project.properties to Env variable
      run: |
        cat project.properties >> $GITHUB_ENV  
    
    - name: Update the Schematic with the git hash
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!Git-${COMMIT}!" *.kicad_sch
        sed -i "s!<<project_name>>!${{ env.project_name }}!" *.kicad_sch
        sed -i "s!<<date>>!$(date +'%Y-%m-%d')!" *.kicad_sch 
        sed -i "s!<<ID>>!${{ env.ID_prefix }}${{ env.ID }}!" *.kicad_sch
        mv *.kicad_sch ${{ env.project_name }}.kicad_sch
    - name: Retrieve results from git hash update
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.project_name }}_Kicad_raw
        path: '${{ env.project_name }}.kicad_sch'

    - name: Run Schematic and BOM 
      run: |
        [ -f *.kicad_sch ] && kiplot  -d Fabrication_temp -s all  print_sch interactive_bom

    - name: Assign variables from project.properties to Env variable
      run: |
        cat project.properties >> $GITHUB_ENV 
    
    - name: Update the PCBs with the git hash
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!Git-${COMMIT}!" *.kicad_pcb
        sed -i "s!<<project_name>>!${{ env.project_name }}!" *.kicad_pcb
        sed -i "s!<<date>>!$(date +'%Y-%m-%d')!" *.kicad_pcb 
        sed -i "s!<<website_link>>!${{ env.Website_link }}/${{ env.ID_prefix }}/${{ env.ID }}!" *.kicad_pcb 
        sed -i "s!<<ID>>!ID: ${{ env.ID_prefix }}${{ env.ID }}!" *.kicad_pcb 
        mv *.kicad_pcb ${{ env.project_name }}.kicad_pcb
    - name: Retrieve results kicad_pcb with the git hash
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.project_name }}_Kicad_raw
        path: '${{ env.project_name }}.kicad_pcb'
    - name: Run PCB stuff
      run: |
        [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp -s all pcb_top_b pcb_bottom_b #print_front print_back
        cd Fabrication_temp
        for file in *; do mv -v ${file} ${{ env.project_name }}_${file}; done #https://unix.stackexchange.com/a/389516
        # mkdir PCB_Sheet
        # mv *Sheet.* PCB_Sheet/
        mkdir BoM
        mv *iBoM.* BoM/

    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.project_name }}_Output
        path: 'Fabrication_temp'

    - name: Run STEP
      run: |
        [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp_step -s all step
    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.project_name }}_Output_STEP
        path: 'Fabrication_temp_step'