name: Release Design

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - 'v*'

  pull_request:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  FabSch:
    name: Schematic fabrication files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: setsoft/kicad_auto:latest

    steps:
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Assign variables from project.properties to Env variable
      run: |
        cat project.properties >> $GITHUB_ENV  
    
    - name: Update the Schematic with the git hash
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!Git-${COMMIT}!" *.sch
        sed -i "s!<<project_name>>!${{ env.project_name }}!" *.sch
        sed -i "s!<<date>>!$(date +'%Y-%m-%d')!" *.sch 
    - name: Retrieve results from git hash update
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.project_name }}_Schematic_raw
        path: 'design.sch'

    - name: Run Schematic and BOM 
      run: |
        [ -f design.sch ] && kiplot -d Fabrication -s all  print_sch interactive_bom 
    #bom_csv
    - name: Retrieve resulted PDF and BOM
      uses: actions/upload-artifact@v1
      with:
        name: FabSch_Output
        path: 'Fabrication'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "Fabrication/*"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}